FROM python:3.12
FROM node:lts

# Setting environment variables for DJANGO
ENV PYTHONUNBUFFERED=1

# Install pip
RUN apt-get update && apt-get install -y python3-pip

# Install Python dependencies:
RUN pip install --upgrade pip --break-system-packages
COPY . .
RUN pip install -r ./requirements.txt --break-system-packages

# Install package.json dependencies
WORKDIR /web_app/frontend
RUN npm install

# Prepare the sqlite database
WORKDIR /web_app
CMD ["python3", "./manage.py", "makemigrations"]
CMD ["python3", "./manage.py", "migrate"]

# Start the server & the webpack script
WORKDIR /web_app/frontend
CMD ["npm", "run", "dev"]

WORKDIR /web_app
CMD ["python3", "./manage.py", "runserver", "0.0.0.0:9000"]

# TODO: MIGHT HAVE TO MODIFY PERMISSIONS FOR WEBPACK